spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guckflix?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  root: info
  org.hibernate.SQL: debug
  # org.hibernate.type: trace